[[members]]
id="106354106196570112"
socials.github="AEnterprise"
socials.twitter="AEnterprise1"
team="core"


[[members]]
id="105076359188979712"
socials.github="BlackHoleFox"
team="core"

[[members]]
id="128181551472050176"
socials.github="trilleplay"
socials.twitter="TristanAtFarkas"
socials.site="https://www.tristanfarkas.se/"
team="contributors"

[[members]]
id="182226567043219456"
socials.github="Taarek"
socials.twitter="Tarek1337_"
team="contributors"

[[members]]
id="298618155281154058"
socials.github="Kitty-Therapist"
team="contributors"

[[members]]
id="117791909786812423"
socials.github="mrkirby153"
socials.twitter="mrkirby153"
team="contributors"

[[members]]
id="257413019787722752"
socials.github="Sem1083"
socials.twitter="Sem010x"
team="contributors"


[[members]]
id="132819036282159104"
socials.github="JohnyTheCarrot"
socials.twitter="JohnyTheCarrot"
team="website"


[[members]]
id="82993510503944192"
socials.twitter="shuu_37"
team="design"


[[members]]
id="267025484028706816"
socials.github="vanishedvan"
socials.twitter="vanishedvan"
team="emoji"